export default {
  allTypes: {
    article: [
      {
        id: 0,
        name: "author",
        label: "Author",
        content: "",
        required: true,
      },
      {
        id: 1,
        name: "title",
        label: "Title",
        content: "",
        required: true,
      },
      {
        id: 2,
        name: "journal",
        label: "Journal",
        content: "",
        required: true,
      },
      {
        id: 3,
        name: "year",
        label: "Year",
        content: "",
        required: true,
      },
      {
        id: 4,
        name: "volume",
        label: "Volume",
        content: "",
        required: false,
      },
    ],
    book: [
      {
        id: 0,
        name: "author",
        label: "Author",
        content: "",
        required: true,
      },
      {
        id: 1,
        name: "title",
        label: "Title",
        content: "",
        required: true,
      },
      {
        id: 2,
        name: "journal",
        label: "Journal",
        content: "",
        required: true,
      },
    ],
    booklet: [
      {
        id: 0,
        name: "title",
        label: "Title",
        content: "",
        required: true,
      },
      {
        id: 1,
        name: "author",
        label: "Author",
        content: "",
        required: false,
      },
    ],
    paper: [
      {
        id: 0,
        name: "title",
        label: "Title",
        content: "",
        required: true,
      },
      {
        id: 1,
        name: "author",
        label: "Author",
        content: "",
        required: true,
      },
      {
        id: 2,
        name: "page_range",
        label: "Page range",
        content: "",
        required: true,
      },
      {
        id: 3,
        name: "abstract",
        label: "Abstract",
        content: "",
        required: true,
      },
      {
        id: 4,
        name: "bibtex_id",
        label: "Bibtex ID",
        content: "",
        required: false,
      },
      {
        id: 5,
        name: "doi",
        label: "DOI",
        content: "",
        required: false,
      },
      {
        id: 6,
        name: "to_appear",
        label: "To appear",
        content: "",
        required: false,
        inputType: "checkbox",
      },
      {
        id: 7,
        name: "detail_url",
        label: "URL",
        content: "",
        required: false,
      },
      {
        id: 8,
        name: "category",
        label: "Category",
        content: "",
        required: false,
      },
      {
        id: 9,
        name: "peer_reviewed",
        label: "Peer reviewed",
        content: "",
        required: false,
        inputType: "checkbox",
      },
    ],
  },
};
