export default {
  allTypes: {
    bibtex_article: [
      {
        id: 0,
        name: "authors",
        label: "Authors",
        content: "",
        required: true,
      },
      {
        id: 1,
        name: "title",
        label: "Title",
        content: "",
        required: true,
      },
      {
        id: 2,
        name: "journal",
        label: "Journal",
        content: "",
        required: true,
      },
      {
        id: 3,
        name: "year",
        label: "Year",
        content: "",
        required: true,
        inputVerify: "number",
      },
      {
        id: 4,
        name: "volume",
        label: "Volume",
        content: "",
        required: false,
        inputVerify: "number",
      },
    ],
    Book: [
      {
        id: 0,
        name: "title",
        label: "Title",
        content: "",
        required: true,
      },
      {
        id: 1,
        name: "authors",
        label: "Authors",
        content: [],
        required: true,
      },
      {
        id: 2,
        name: "year",
        label: "Year",
        content: "",
        required: true,
        inputVerify: "number",
      },
      {
        id: 3,
        name: "volume",
        label: "Volume",
        content: "",
        required: true,
        inputVerify: "number",
      },
      {
        id: 4,
        name: "category",
        label: "Category",
        content: "",
        required: true,
      },
      {
        id: 5,
        name: "bookAbstract",
        label: "Abstract",
        content: "",
        required: true,
      },
      {
        id: 6,
        name: "isbn",
        label: "ISBN",
        content: "",
        required: true,
      },
    ],
    Paper: [
      {
        id: 0,
        name: "title",
        label: "Title",
        content: "",
        required: true,
      },
      {
        id: 1,
        name: "authors",
        label: "Authors",
        content: [],
        required: true,
      },
      {
        id: 2,
        name: "category",
        label: "Category",
        content: "",
        required: false,
      },
      {
        id: 3,
        name: "paperAbstract",
        label: "Abstract",
        content: "",
        required: true,
      },
      {
        id: 4,
        name: "peer_reviewed",
        label: "Peer reviewed",
        content: "",
        required: false,
        inputType: "checkbox",
      },
    ],
  },
};
