export default {
  allTypes: {
    bibtex_article: [
      {
        id: 0,
        name: "author",
        label: "Author",
        content: "",
        required: true,
      },
      {
        id: 1,
        name: "title",
        label: "Title",
        content: "",
        required: true,
      },
      {
        id: 2,
        name: "journal",
        label: "Journal",
        content: "",
        required: true,
      },
      {
        id: 3,
        name: "year",
        label: "Year",
        content: "",
        required: true,
      },
      {
        id: 4,
        name: "volume",
        label: "Volume",
        content: "",
        required: false,
      },
    ],
    book: [
      {
        id: 0,
        name: "title",
        label: "Title",
        content: "",
        required: true,
      },
      {
        id: 1,
        name: "author",
        label: "Author",
        content: "",
        required: true,
      },
      {
        id: 2,
        name: "year",
        label: "Year",
        content: "",
        required: true,
        inputVerify: "number",
      },
      {
        id: 3,
        name: "volume",
        label: "Volume",
        content: "",
        required: true,
      },
      {
        id: 4,
        name: "edition",
        label: "Edition",
        content: "",
        required: true,
      },
      {
        id: 5,
        name: "number_of_pages",
        label: "Number of pages",
        content: "",
        required: true,
        inputVerify: "number",
      },
      {
        id: 6,
        name: "cities",
        label: "Cities",
        content: "",
        required: false,
      },
      {
        id: 7,
        name: "isbn",
        label: "ISBN",
        content: "",
        required: false,
      },
      {
        id: 8,
        name: "abstract",
        label: "Abstract",
        content: "",
        required: true,
      },
      {
        id: 9,
        name: "bibtex_id",
        label: "Bibtex ID",
        content: "",
        required: false,
      },
      {
        id: 10,
        name: "doi",
        label: "DOI",
        content: "",
        required: false,
        inputVerify: "url",
      },
      {
        id: 11,
        name: "to_appear",
        label: "To appear",
        content: "",
        required: false,
        inputType: "checkbox",
      },
      {
        id: 12,
        name: "detail_url",
        label: "URL",
        content: "",
        required: false,
        inputVerify: "url",
      },
      {
        id: 13,
        name: "category",
        label: "Category",
        content: "",
        required: false,
      },
      {
        id: 14,
        name: "shop_url",
        label: "Shop URL",
        content: "",
        required: false,
        inputVerify: "url",
      },
      {
        id: 15,
        name: "cover_url",
        label: "Cover URL",
        content: "",
        required: false,
        inputVerify: "url",
      },
    ],
    paper: [
      {
        id: 0,
        name: "title",
        label: "Title",
        content: "",
        required: true,
      },
      {
        id: 1,
        name: "author",
        label: "Author",
        content: "",
        required: true,
      },
      {
        id: 2,
        name: "page_range",
        label: "Page range",
        content: "",
        required: true,
      },
      {
        id: 3,
        name: "abstract",
        label: "Abstract",
        content: "",
        required: true,
      },
      {
        id: 4,
        name: "bibtex_id",
        label: "Bibtex ID",
        content: "",
        required: false,
      },
      {
        id: 5,
        name: "doi",
        label: "DOI",
        content: "",
        required: false,
        inputVerify: "url",
      },
      {
        id: 6,
        name: "to_appear",
        label: "To appear",
        content: "",
        required: false,
        inputType: "checkbox",
      },
      {
        id: 7,
        name: "detail_url",
        label: "URL",
        content: "",
        required: false,
        inputVerify: "url",
      },
      {
        id: 8,
        name: "category",
        label: "Category",
        content: "",
        required: false,
      },
      {
        id: 9,
        name: "peer_reviewed",
        label: "Peer reviewed",
        content: "",
        required: false,
        inputType: "checkbox",
      },
    ],
    journal: [
      {
        id: 0,
        name: "long_name",
        label: "Long name",
        content: "",
        required: true,
      },
      {
        id: 1,
        name: "short_name",
        label: "Short name",
        content: "",
        required: true,
      },
      {
        id: 1,
        name: "issn",
        label: "ISSN",
        content: "",
        required: false,
      },
      {
        id: 1,
        name: "eissn",
        label: "EISSN",
        content: "",
        required: false,
      },
    ],
  },
};
