# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Test

on:
  push:
    branches: [ main, action_test ]
  pull_request:
    branches: [ main, action_test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@v2
    
    # Get java
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    # Build
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Move output to staging directory
      run: mkdir staging && cp target/*.jar staging
    
    - name: Upload build output as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging
